---
- hosts: all
  vars:
    user_name: alinz
    user_email: "{{ user_name }}@email-provider.com"
    domain: "{{ var_domain | default('klingt.net') }}"
    domain_version: unknown
    caddy_email: "{{ user_email }}"
    caddy_restic_user: alinz
    web_root: /var/web
  vars_files:
    - vault_vars.yml
  roles:
    - common
    - postgres
    - gitea
    - jupyter
    - caddy
    - prometheus
    - grafana
    - klingt.net
  tasks:
  - name: Set version number
    delegate_to: localhost
    shell: git describe --always --tags
    register: git_version
  - set_fact:
      domain_version: "{{ git_version.stdout }}"
