---
- hosts: all
  gather_facts: false # see pre_tasks
  vars:
    user_name: alinz
    user_email: admin@klingt.net
    is_staging: "{{ var_staging | default(False) }}"
    domain: "{{ var_domain | default('klingt.net') }}"
    domain_version: unknown
    caddy_email: "{{ user_email }}"
    web_root: /var/web
  vars_files:
    - vault_vars.yml
  roles:
    - common
    - postgres
    - gitea
    - jupyter
    - prometheus
    - grafana
    - caddy
    - klingt.net
  pre_tasks:
    - name: Setup Python 2.x
      raw: test -e /usr/bin/python2 || (sudo apt -y update && sudo apt install -y python-minimal)
    - setup: # gather facts
