---
- hosts: all
  vars:
    user_name: alinz
    user_email: admin@klingt.net
    is_staging: "{{ var_staging | default(False) }}"
    domain: "{{ var_domain | default('klingt.net') }}"
    domain_version: unknown
    caddy_email: "{{ user_email }}"
    caddy_restic_user: alinz
    web_root: /var/web
  vars_files:
    - vault_vars.yml
  roles:
    - common
    - postgres
    - gitea
    - jupyter
    - prometheus
    - grafana
    - droneci
    - caddy
    - klingt.net
    - goaccess
