- name: "Create {{ web_root }}"
  file:
    state: directory
    path: "{{ web_root }}/{{ domain }}"
    mode: 0755
  become: true
- name: "Extract klingt.net backup"
  unarchive:
    src: kn-september-2017.tar.xz
    dest: "{{ web_root }}/{{ domain }}"
    group: "{{ caddy_group }}"
    owner: "{{ caddy_user }}"
  become: true
