- name: Build klingt.net
  command: make -B -C ./build/klingt.net
  delegate_to: localhost
- name: "Create {{ web_root }}"
  file:
    state: directory
    path: "{{ web_root }}/{{ domain }}"
    mode: 0755
  become: true
- name: Copy templated website
  copy:
    src: ./build/klingt.net/out/
    dest: "{{ web_root }}/{{ domain }}"
    group: "{{ caddy_group }}"
    owner: "{{ caddy_user }}"
  become: true
