- name: Install Julia
  apt:
    package: julia
  become: true
- name: Install IJulia
  command: julia --eval 'try if Pkg.installed("IJulia") == nothing Pkg.add("IJulia") end catch end'
  become: true
  become_user: "{{ jupyter_user }}"
